server:
  port: 8085

eureka:
  client:
    service-url: 
      defaultZone: http://localhost:8099/eureka/
      
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routers:
        - id: service-customer
          uri: lb://service-customer
          predicate:
            - Path=/customers/**
        - id: service-product
          uri: lb://service-product
          predicate:
            - Path=/products/**
        - id: service-shopping
          uri: lb://service-shopping
          predicate:
            - Path=/invoices/**
