server:
  port: 8092
  
spring:
 h2: 
  console:
   enabled: true
  datasource:
    url: jdbc:h2:mem;DB_CLOSE_DELAY=-1;
    driver-class-name: org.h2.Driver
    platform: h2
    username: sa
    password: 
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
       show_sql: true
       use_sql_coment: false
       format_sql: false
logging:
  pattern:
    console: "%d{yyy-MM-dd HH:mm:ss} ${log_level_pattern:-%5p} %m%n"

eureka:
  client:
    service-url: http://localhost:8099/eureka/

